### PR TITLE
Fix mac compiler error

### PR DESCRIPTION
**Pull request by jasonatball**
Cast 0 to void* ptr

### CODE REVIEW

**Comment by jasonatball** [comment]
Fixes #150

**Comment by jasonatball** [comment]
As a part of this release we should consider dropping Ruby 2.0 support and trying to add Ruby 2.4.

**Comment by ryanatball** [comment]
:+1:

**Comment by mmladenovski** [comment]
Hi @ryanatball , in which gem version are we going to see this fix?

**Comment by ryanatball** [comment]
Fix will be in qtbindings 4.8.6.4 (next week).

**Comment by mmladenovski** [comment]
Thanks @ryanatball

**Pull request merged**
